trigger:
  - main
  - cicd

resources:
  - repo: self

variables:
  - group: DCD
  - group: DCD-KeyVault
  - name: vmImageName
    value: "ubuntu-latest"
stages:
  - template: templates/stage-build.yml
    parameters:
      workSpace: $(Pipeline.Workspace)
      buildId: $(Build.BuildId)
      dt_tenant: $(dynatrace_tenant)
      dt_password: $(dynatrace-prod-token)
      dt_url: $(dynatrace_baseurl)
      sourcesDirectory: $(Build.SourcesDirectory)
      name: "DCD"

  - template: templates/stage-deploy.yml
    parameters:
      imageTag: $(Build.BuildId)
      webAppName: "ase-dcd"
      serviceConnection: "dcd-pipeline-sp"
      name: DeployDev
      environment: dev

  - template: templates/stage-deploy.yml
    parameters:
      imageTag: $(Build.BuildId)
      webAppName: "ase-dcd"
      serviceConnection: "dcd-pipeline-sp"
      name: DeployQA
      environment: qa
